ARG VERSION
FROM almalinux:${VERSION:-9}
ARG COURSE="DOCKER" \
    TRAINER="TULASI"

ENV COURSE=${COURSE}  
RUN echo "Trainer: ${TRAINER}, Course: ${COURSE}, VErsion: ${VERSION}"
CMD ["sleep","1000"]

    